### ISSUE TITLE
Does quic-conn support Timeout, ReadTimeout and WriteTimeout?

### ISSUE THREAD

**Issue by smallnest** [marten-seemann/quic-conn#10]
Does quic-conn support Timeout, ReadTimeout and WriteTimeout?

And if the peer(server) is restarted, can the client continue to send data to the peer? It seems client hangs and closed after 240s.

> NetworkIdleTimeout: No recent network activity.

**Comment by marten-seemann** [comment]
`ReadTimeout` and `WriteTimeout` are properties of the [http.Server](https://golang.org/pkg/net/http/#Server). If you're interested in speaking HTTP over QUIC have a look at the h2quic package of https://github.com/lucas-clemente/quic-go/.

When the server is restarted, it loses all cryptographic state, so you'll have to establish a new QUIC connection in that case.

**Comment by smallnest** [comment]
Yes, I will recreate a connection if I find the connection is broken. But it looks  it passed 240 seconds that we are nodified that the connection is broken  after the server restarted. So I want to know there is an approach to notify the client as early as possible, for example, Timeout parameter or others.

**Comment by smallnest** [comment]
Can those methods be implemented?

```go

func (c *conn) SetDeadline(t time.Time) error {
--
  | return nil
  | }
  |  
  | func (c *conn) SetReadDeadline(t time.Time) error {
  | return nil
  | }
  |  
  | func (c *conn) SetWriteDeadline(t time.Time) error {
  | return nil
  | }


```

**Comment by smallnest** [comment]
I found a related issue:  https://github.com/lucas-clemente/quic-go/issues/514

**Comment by marten-seemann** [comment]
Deadlines and timeouts are completely different things. Deadlines won't help here.

The problem here is that the PUBLIC_RESET is currently not read by the client (https://github.com/lucas-clemente/quic-go/issues/34). A PUBLIC_RESET is sent by the server when it receives an undecryptable packet for an unknown connection (which is how the server would interpret every client packet after the restart).

**Comment by marten-seemann** [comment]
I just implemented PUBLIC_RESET receiving for the client in https://github.com/lucas-clemente/quic-go/pull/729. This should fix this issue.

Please update your dependencies and try again. Feel free to reopen this issue if it doesn't work.
