### ISSUE TITLE
Error after latest update in quic-go

### ISSUE THREAD

**Issue by danielpeng6** [marten-seemann/quic-conn#13]
github.com/lucas-clemente/quic-go/vendor/github.com/marten-seemann/qtls
../../../lucas-clemente/quic-go/vendor/github.com/marten-seemann/qtls/common.go:300:18: undefined: tls.ECDSAWithSHA1
../../../lucas-clemente/quic-go/vendor/github.com/marten-seemann/qtls/common.go:1196:2: internal compiler error: unexpected Interface for <nil>

**Comment by marten-seemann** [comment]
The CI didn't complain. Please check your Go version and your dependencies.
