### ISSUE TITLE
Can you help me while I used go1.11. 5 with an error 

### ISSUE THREAD

**Issue by ebel2000** [marten-seemann/quic-conn#15]
#go get github.com/marten-seemann/quic-conn

src/github.com/marten-seemann/quic-conn/conn.go:31:48: not enough arguments in call to c.session.AcceptStream
        have ()
        want (context.Context)
src/github.com/marten-seemann/quic-conn/server.go:17:34: not enough arguments in call to s.quicServer.Accept
        have ()
        want (context.Context)

**Comment by marten-seemann** [comment]
Please make sure you have Go modules enables (`GO111MODULE=on`).

**Comment by ebel2000** [comment]
Thank you very much, The problem is solved.




------------------ 原始邮件 ------------------
发件人: "Marten Seemann"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 下午3:13
收件人: "marten-seemann/quic-conn"<quic-conn@noreply.github.com>;
抄送: "任玉宝"<493949879@QQ.COM>;"Author"<author@noreply.github.com>;
主题: Re: [marten-seemann/quic-conn] Can you help me while I used go1.11. 5with an error  (#15)




Please make sure you have Go modules enables (GO111MODULE=on).
