### ISSUE TITLE
close the read stream

### ISSUE THREAD

**Issue by marten-seemann** [marten-seemann/quic-conn#5]
Streams are used uni-directionally, so the incoming stream should be closed as soon as it is accepted.

**Comment by antong** [comment]
BTW, why do conns need separate, unidirectional receive and send streams? Couldn't I just use a single stream bidirectionally as in the `quic-go/example/echo/echo.go example`?

**Comment by marten-seemann** [comment]
No, because the QUIC spec defines which peer has to open a certain stream.
