### ISSUE TITLE
build failure because quic.Config has removed TLSConfig

### ISSUE THREAD

**Issue by smallnest** [marten-seemann/quic-conn#9]
Since quic-go has removed TLSConfig from Config struct, quic-conn should keep consistent with it.
My project [rpcx](https://github.com/smallnest/rpcx) has supported quic based on this project but now some guys reported they can't build the project.

**Comment by marten-seemann** [comment]
Thanks for reporting! I fixed it in 57a9a2dddfb102756e71c3ca5c352d9852d284ce.

Feel free to open new issues if you have any other problems.

**Comment by smallnest** [comment]
Thanks @marten-seemann
